// Global content library — all subjects, lessons, questions, flashcards
// Automatically assigned to every new user's study plan

export type LessonData = { title: string; topic: string; type: string; duration: number; content: string };
export type QuestionData = {
  topic: string; content: string; banca: string; difficulty: string; year: number; explanation: string;
  options: { letter: string; text: string; isCorrect: boolean }[];
};
export type FlashcardData = { question: string; answer: string };

export type SubjectData = {
  name: string;
  weeklyHours: number;
  priority: number;
  lessons: LessonData[];
  questions: QuestionData[];
  flashcards: FlashcardData[];
};

export const CONTENT_LIBRARY: SubjectData[] = [
  {
    name: "Português",
    weeklyHours: 4,
    priority: 1,
    flashcards: [
      { question: "O que é sujeito oculto?", answer: "Sujeito não expresso, identificável pela desinência verbal. Ex: 'Estudamos.' = nós" },
      { question: "'Haver' no sentido de existir é pessoal ou impessoal?", answer: "IMPESSOAL — sempre singular. 'Houve problemas.' (nunca 'houveram')" },
      { question: "Qual a diferença entre 'mau' e 'mal'?", answer: "'Mau' é adjetivo (antônimo de bom). 'Mal' é advérbio (antônimo de bem)." },
      { question: "Quando usar vírgula com adjunto adverbial?", answer: "Adjunto adverbial DESLOCADO (no início da oração) = vírgula obrigatória." },
      { question: "O que são verbos de ligação?", answer: "Ser, estar, ficar, parecer, continuar, tornar-se, permanecer. Ligam sujeito ao predicativo." },
    ],
    lessons: [
      { title: "Morfologia — Classes de Palavras", topic: "Morfologia", type: "video", duration: 12, content: `AS 10 CLASSES GRAMATICAIS\n\n1. SUBSTANTIVO — nomeia seres, objetos, sentimentos\n   Próprio: Brasil, Pedro | Comum: cidade, aluno\n   Concreto: mesa, livro | Abstrato: amor, justiça\n   Coletivo: alcateia (lobos), cardume (peixes)\n\n2. ADJETIVO — caracteriza o substantivo\n   "O candidato DEDICADO foi aprovado."\n   INVARIÁVEIS: "menos", "alerta", "pseudo"\n\n3. ARTIGO — determina o substantivo\n   Definidos: o, a, os, as\n   Indefinidos: um, uma, uns, umas\n\n4. NUMERAL — quantidade, ordem ou fração\n   Cardinal: um, dois | Ordinal: primeiro\n   Fracionário: metade, terço | Multiplicativo: dobro\n\n5. PRONOME — substitui ou acompanha o substantivo\n   Pessoal: eu, tu, ele, nós, vós, eles\n   Possessivo: meu, teu, seu, nosso\n   Demonstrativo: este (perto), esse (médio), aquele (longe)\n   Relativo: que, quem, cujo, onde, o qual\n\n6. VERBO — ação, estado ou fenômeno\n   Regulares: amar, comer, partir\n   Irregulares: ser, ir, vir, fazer, ter\n   Impessoais: chover, haver (existir), fazer (tempo)\n\n7. ADVÉRBIO — modifica verbo, adjetivo ou outro advérbio\n   INVARIÁVEL em gênero e número\n   Modo: bem, mal, assim | Tempo: ontem, hoje, sempre\n   Lugar: aqui, ali, lá | Intensidade: muito, pouco, bastante\n\n8. PREPOSIÇÃO — liga palavras\n   Simples: a, ante, após, até, com, contra, de, em, entre,\n            para, per, perante, por, sem, sob, sobre, trás\n\n9. CONJUNÇÃO — une orações\n   Coordenativas: e (adição), mas/porém (oposição), ou (alternativa),\n                 logo/portanto (conclusão), pois (explicação)\n   Subordinativas: que (substantiva), porque (causal), embora (concessiva),\n                  se (condicional), quando (temporal)\n\n10. INTERJEIÇÃO — expressa emoção (Ah! Oh! Ufa! Eba! Caramba!)\n\nDICA CONCURSO: Identifique a classe pela FUNÇÃO na frase, não pela forma.` },
      { title: "Sintaxe — Sujeito e Predicado", topic: "Sintaxe", type: "reading", duration: 15, content: `SUJEITO — ser sobre o qual se declara algo\n\nTIPOS DE SUJEITO:\n\n• SIMPLES (1 núcleo): "O candidato estudou."\n• COMPOSTO (2+ núcleos): "Pedro e Ana passaram."\n• OCULTO/ELÍPTICO (identificado pelo verbo): "Estudamos muito." (= nós)\n• INDETERMINADO (não identificável): "Precisa-se de servidores."\n• INEXISTENTE (verbos impessoais):\n  - Fenômenos: chover, nevar, amanhecer\n  - HAVER (existir): "Houve problemas." (NUNCA houveram)\n  - FAZER (tempo): "Faz dois anos." (NUNCA fazem)\n  - SER (tempo/distância): "São 8 horas." / "É longe."\n\nPREDICADO — tudo que se declara sobre o sujeito:\n• VERBAL: verbo significativo — "O aluno estudou."\n• NOMINAL: VL + predicativo — "Ele está preparado."\n• VERBO-NOMINAL: ambos — "Chegou cansado."\n\nVERBOS DE LIGAÇÃO (VL): ser, estar, ficar, parecer,\ncontinuar, tornar-se, permanecer, andar, viver\n\nREGRAS IMPORTANTES:\n✓ NÃO se separa sujeito do predicado com vírgula\n✓ HAVER impessoal = sempre singular\n✓ FAZER indicando tempo = sempre singular\n✓ EXISTIR é pessoal: "Existem soluções." (sujeito: "soluções")` },
      { title: "Concordância Verbal — Casos Especiais", topic: "Sintaxe", type: "video", duration: 18, content: `CONCORDÂNCIA VERBAL — REGRAS E PEGADINHAS\n\nREGRA GERAL: verbo concorda em número e pessoa com o sujeito.\n\n1. EXPRESSÕES PARTITIVAS (a maioria de, a maior parte de)\n   → Verbo pode ir ao singular OU ao plural\n   "A maioria dos candidatos passou/passaram." ✓\n\n2. COLETIVO + COMPLEMENTO\n   → Singular (com o coletivo)\n   "O grupo de alunos estudou muito."\n\n3. PRONOMES RELATIVOS (que, quem)\n   → Concorda com o antecedente\n   "Fui eu que resolvi." ✓ / "Fui eu quem resolveu." ✓\n\n4. PORCENTAGEM\n   Com artigo antes do numeral → concorda com numeral\n   "Os 30% dos candidatos foram aprovados."\n   Sem artigo → pode concordar com o complemento\n   "30% da turma foi/foram aprovada(s)." ✓\n\n5. PRONOMES INDEFINIDOS\n   → Verbo no singular: ninguém, nenhum, cada, alguém, tudo, nada\n   "Ninguém foi reprovado."\n\n6. SUJEITO COMPOSTO PÓS-VERBAL\n   → Pode concordar com o mais próximo\n   "Passou o candidato e a examinadora." ✓\n   "Passaram o candidato e a examinadora." ✓\n\n7. "UM DOS QUE"\n   → Verbo no plural\n   "Ela é uma das que mais estudaram."\n\nPEGADINHAS CLÁSSICAS:\n❌ "Houveram problemas" → ✓ "Houve problemas"\n❌ "Fazem dois anos" → ✓ "Faz dois anos"\n❌ "Haviam vagas" → ✓ "Havia vagas"\n❌ "Existia várias formas" → ✓ "Existiam várias formas"` },
      { title: "Concordância Nominal e Regência", topic: "Gramática", type: "reading", duration: 20, content: `CONCORDÂNCIA NOMINAL\nAdjetivos concordam em gênero e número com o substantivo.\n\nCASOS ESPECIAIS:\n1. Adjetivo após dois substantivos\n   → Concorda com o mais próximo OU vai ao plural\n   "Tenho lápis e caneta novos." / "Tenho caneta e lápis nova."\n\n2. INVARIÁVEIS: menos, alerta, pseudo, extra, anti, semi, meio (advérbio)\n   "As meninas estão alerta." (não "alertas")\n   "Meio metro de tecido." (não "meia")\n   MAS: "Ela comeu meia laranja." (adj. = meia)\n\n3. Predicativo antes do sujeito composto → singular\n   "É proibido bebidas alcoólicas e cigarros."\n\nREGÊNCIA VERBAL — preposições exigidas pelos verbos:\n\n• ASSISTIR (ver/presenciar) + A → "Assisti AO jogo."\n• ASSISTIR (ajudar) sem prep. → "O médico assistiu o paciente."\n• VISAR (objetivar) + A → "Visa AO lucro."\n• VISAR (aplicar visto) sem prep. → "Visou o documento."\n• PREFERIR + A → "Prefiro estudo A lazer."\n  ❌ NUNCA: "prefiro mais" / "prefiro do que"\n• OBEDECER/DESOBEDECER + A → "Obedeceu AO regulamento."\n• IMPLICAR (acarretar) sem prep. → "Implica mudança."\n• IMPLICAR (irritar) + COM → "Implica COM tudo."\n• NAMORAR sem prep. → "Namora Maria." (NÃO "namora com")\n\nREGÊNCIA NOMINAL:\n• DISTANTE/PRÓXIMO + DE → "Distante DO objetivo."\n• FAVORÁVEL/CONTRÁRIO + A → "Favorável AO projeto."\n• DIFERENTE/SEMELHANTE + DE → "Diferente DO esperado."` },
      { title: "Exercícios — Concordância e Sintaxe", topic: "Sintaxe", type: "exercise", duration: 25, content: `QUESTÕES COMENTADAS\n\nQ1. Indique a alternativa CORRETA:\nA) Houveram muitas vagas abertas. ❌ (haver impessoal = singular)\nB) Houve muitas vagas abertas. ✓\nC) Haviam poucas oportunidades. ❌\nD) Fazem três anos que não chove. ❌ (fazer = impessoal)\nE) Existia várias soluções. ❌ (existir = pessoal)\n\nQ2. O sujeito de "Choveu muito ontem" é:\nA) "ontem" ❌  B) Inexistente ✓  C) Oculto ❌  D) Indeterminado ❌\n→ CHOVER = fenômeno da natureza = impessoal = sem sujeito\n\nQ3. "Assistimos AO jogo." O uso da preposição é:\nA) Errado — assistir não exige preposição ❌\nB) Correto — assistir (ver) exige A ✓\nC) Facultativo ❌\nD) Errado — deveria ser "no jogo" ❌\n\nQ4. Em "Comprei caneta e lápis novo", o adjetivo:\nA) Está errado ❌\nB) Concorda com "lápis" (mais próximo) ✓\nC) Deve ser "novos" obrigatoriamente ❌\nD) Deve ser "nova" obrigatoriamente ❌\n\nQ5. Qual frase tem erro de regência?\nA) "Prefiro café a chá." ✓ correto\nB) "Prefiro mais café do que chá." ❌ ERRADO — "prefiro" já indica comparação\nC) "Visa ao cargo público." ✓ correto\nD) "Obedeceu ao regulamento." ✓ correto\n→ RESPOSTA: B` },
    ],
    questions: [
      { topic: "Concordância Verbal", content: "Assinale a alternativa em que a concordância verbal está CORRETA de acordo com a norma culta.", banca: "CESPE", difficulty: "medium", year: 2023, explanation: "HAVER no sentido de existir é IMPESSOAL, ficando sempre no singular. Já EXISTIR é pessoal e concorda com o sujeito.", options: [{ letter: "A", text: "Houve muitas vagas abertas no concurso.", isCorrect: true }, { letter: "B", text: "Houveram muitos candidatos inscritos.", isCorrect: false }, { letter: "C", text: "Haviam poucas questões de Português.", isCorrect: false }, { letter: "D", text: "Fizeram dois anos que não houve concurso.", isCorrect: false }, { letter: "E", text: "Existia várias opções de gabarito.", isCorrect: false }] },
      { topic: "Sintaxe", content: "O sujeito da oração 'Choveu torrencialmente durante todo o mês' é:", banca: "FCC", difficulty: "easy", year: 2022, explanation: "CHOVER é verbo impessoal (fenômeno da natureza), portanto a oração não tem sujeito. Orações sem sujeito: verbos de fenômenos naturais, HAVER (existir), FAZER (tempo), SER (tempo/distância).", options: [{ letter: "A", text: "Simples: 'o mês'", isCorrect: false }, { letter: "B", text: "Oculto: identificado pelo contexto", isCorrect: false }, { letter: "C", text: "Inexistente, pois 'chover' é impessoal", isCorrect: true }, { letter: "D", text: "Indeterminado", isCorrect: false }, { letter: "E", text: "Composto: 'chuva' e 'mês'", isCorrect: false }] },
      { topic: "Regência Verbal", content: "Assinale a frase com uso CORRETO da regência verbal:", banca: "CESPE", difficulty: "hard", year: 2024, explanation: "PREFERIR exige a preposição A para introduzir o segundo elemento da comparação. NUNCA se usa 'mais' ou 'do que' com PREFERIR, pois esses elementos já estão implícitos no significado do verbo.", options: [{ letter: "A", text: "Prefiro estudar do que trabalhar.", isCorrect: false }, { letter: "B", text: "Prefiro estudo a lazer.", isCorrect: true }, { letter: "C", text: "Prefiro mais a prática que a teoria.", isCorrect: false }, { letter: "D", text: "Assistiram no jogo pela televisão.", isCorrect: false }, { letter: "E", text: "Namora com a mesma pessoa há anos.", isCorrect: false }] },
      { topic: "Concordância Nominal", content: "Em qual alternativa a concordância nominal está CORRETA?", banca: "VUNESP", difficulty: "medium", year: 2023, explanation: "ALERTA é invariável — não flexiona em gênero nem número. Outros invariáveis comuns: menos, pseudo, extra, anti, meio (como advérbio).", options: [{ letter: "A", text: "Os candidatos estavam alertas para as mudanças.", isCorrect: false }, { letter: "B", text: "Os candidatos estavam alerta para as mudanças.", isCorrect: true }, { letter: "C", text: "Ela comeu meios pãos no café da manhã.", isCorrect: false }, { letter: "D", text: "A banca é menas exigente que a anterior.", isCorrect: false }, { letter: "E", text: "É proibidos cigarros e bebidas neste local.", isCorrect: false }] },
    ],
  },

  {
    name: "Raciocínio Lógico",
    weeklyHours: 3,
    priority: 2,
    flashcards: [
      { question: "Quando a condicional p→q é FALSA?", answer: "Somente quando p é V e q é F. Nos outros três casos (V→V, F→V, F→F) é verdadeira." },
      { question: "O que é a contrapositiva de p→q?", answer: "É ~q→~p. SEMPRE logicamente equivalente à condicional original." },
      { question: "Qual a negação de 'Todo A é B'?", answer: "'Algum A NÃO é B' — negação do quantificador universal." },
      { question: "Fórmula da união de dois conjuntos?", answer: "|A∪B| = |A| + |B| - |A∩B|" },
      { question: "O que é De Morgan?", answer: "~(p∧q) = ~p∨~q e ~(p∨q) = ~p∧~q — negação inverte o conectivo e nega cada parte." },
    ],
    lessons: [
      { title: "Proposições e Conectivos Lógicos", topic: "Lógica Proposicional", type: "video", duration: 14, content: `LÓGICA PROPOSICIONAL — FUNDAMENTOS\n\nPROPOSIÇÃO: frase declarativa com valor V ou F\n✓ "O Brasil é sul-americano." (V)\n✓ "2 + 2 = 5" (F)\n✗ "Feche a porta!" (imperativo)\n✗ "x + 2 = 5" (valor indefinido)\n\nCONECTIVOS E TABELAS-VERDADE:\n\n¬ NEGAÇÃO: inverte o valor — ¬V=F | ¬F=V\n\n∧ CONJUNÇÃO "e": V somente quando AMBAS V\nV∧V=V | V∧F=F | F∧V=F | F∧F=F\n\n∨ DISJUNÇÃO "ou" (inclusivo): F somente quando AMBAS F\nV∨V=V | V∨F=V | F∨V=V | F∨F=F\n\n→ CONDICIONAL "se...então": F somente quando V→F\nV→V=V | V→F=F ← ÚNICO FALSO\nF→V=V | F→F=V\n\n↔ BICONDICIONAL: V quando IGUAIS\nV↔V=V | V↔F=F | F↔V=F | F↔F=V\n\nEQUIVALÊNCIAS FUNDAMENTAIS:\n~(p→q) ≡ p∧~q         (negação da condicional)\np→q ≡ ~q→~p           (contrapositiva — SEMPRE equivalente)\n~(p∧q) ≡ ~p∨~q        (De Morgan)\n~(p∨q) ≡ ~p∧~q        (De Morgan)\np→q ≡ ~p∨q            (outra forma da condicional)` },
      { title: "Quantificadores e Silogismos", topic: "Lógica de Predicados", type: "reading", duration: 16, content: `QUANTIFICADORES LÓGICOS\n\n∀ UNIVERSAL "todo, qualquer, nenhum"\n"Todo servidor é honesto."\nNegação: "Algum servidor NÃO é honesto."\n\n∃ EXISTENCIAL "algum, existe"\n"Algum servidor é honesto."\nNegação: "Nenhum servidor é honesto."\n\nTABELA DE NEGAÇÕES:\n~(Todo A é B) = Algum A não é B\n~(Nenhum A é B) = Algum A é B\n~(Algum A é B) = Nenhum A é B\n~(Algum A não é B) = Todo A é B\n\nSILOGISMO — raciocínio dedutivo:\nPremissa 1: Todo A é B\nPremissa 2: Todo B é C\nConclusão: Logo, todo A é C ✓\n\nARGUMENTOS VÁLIDOS CLÁSSICOS:\n• Modus Ponens: Se p→q e p, então q\n• Modus Tollens: Se p→q e ~q, então ~p\n• Silogismo Hipotético: Se p→q e q→r, então p→r\n\nEXEMPLO COBRADO:\n"Se chover, o jogo cancela."\n"O jogo não cancelou."\nConclusão: "Não choveu." ← Modus Tollens ✓\n\nNÃO é válido:\n"Se chover, o jogo cancela."\n"Não choveu."\nConclusão: "O jogo aconteceu." ← FALÁCIA (pode ter cancelado por outra razão)` },
      { title: "Teoria dos Conjuntos e Probabilidade", topic: "Conjuntos", type: "video", duration: 18, content: `TEORIA DOS CONJUNTOS\n\nFÓRMULA DA UNIÃO:\n|A∪B| = |A| + |B| - |A∩B|\n\nCom 3 conjuntos:\n|A∪B∪C| = |A|+|B|+|C| - |A∩B| - |A∩C| - |B∩C| + |A∩B∩C|\n\nEXEMPLO CLÁSSICO:\n40 pessoas: 25 falam inglês, 18 espanhol, 10 os dois.\n|A∪B| = 25+18-10 = 33\nNinguém fala nenhum = 40-33 = 7 pessoas\n\nPRINCÍPIO FUNDAMENTAL DA CONTAGEM:\nn1 × n2 × n3 × ...\nEx: 3 camisas e 4 calças = 3×4 = 12 combinações\n\nPERMUTAÇÃO (arranjo de todos):\nP(n) = n!\nP(4) = 4×3×2×1 = 24\n\nCOMBINAÇÃO (grupos sem ordem):\nC(n,k) = n! / (k! × (n-k)!)\nC(5,2) = 5!/(2!×3!) = 10\n\nPROBABILIDADE:\nP(A) = casos favoráveis / casos totais\nP(A∪B) = P(A) + P(B) - P(A∩B)\nP(A∩B) = P(A) × P(B) [se independentes]\nP(A|B) = P(A∩B)/P(B) [probabilidade condicional]` },
    ],
    questions: [
      { topic: "Lógica Proposicional", content: "Se p é verdadeiro e q é falso, qual é o valor lógico de (p → q) ∨ (¬p ∧ q)?", banca: "CESPE", difficulty: "hard", year: 2023, explanation: "p→q: V→F=F. ¬p∧q: F∧F=F. F∨F=FALSO. A condicional só é falsa quando antecedente é V e consequente é F.", options: [{ letter: "A", text: "Verdadeiro", isCorrect: false }, { letter: "B", text: "Falso", isCorrect: true }, { letter: "C", text: "Indeterminado", isCorrect: false }, { letter: "D", text: "Equivalente a p", isCorrect: false }, { letter: "E", text: "Equivalente a ~q", isCorrect: false }] },
      { topic: "Teoria dos Conjuntos", content: "Em uma turma de 60 alunos, 35 estudam Português, 28 estudam Matemática e 12 estudam ambas. Quantos não estudam nenhuma das duas?", banca: "FCC", difficulty: "medium", year: 2022, explanation: "|P∪M| = 35+28-12 = 51. Não estudam nenhuma = 60-51 = 9 alunos. Atenção ao não esquecer de subtrair a interseção.", options: [{ letter: "A", text: "7", isCorrect: false }, { letter: "B", text: "9", isCorrect: true }, { letter: "C", text: "11", isCorrect: false }, { letter: "D", text: "15", isCorrect: false }, { letter: "E", text: "21", isCorrect: false }] },
      { topic: "Quantificadores", content: "A negação de 'Todo servidor público é eficiente e dedicado' é:", banca: "CESPE", difficulty: "hard", year: 2024, explanation: "~(∀x: p∧q) = ∃x: ~(p∧q) = ∃x: ~p∨~q (De Morgan). 'Algum servidor público não é eficiente OU não é dedicado.'", options: [{ letter: "A", text: "Nenhum servidor público é eficiente e dedicado.", isCorrect: false }, { letter: "B", text: "Algum servidor público não é eficiente ou não é dedicado.", isCorrect: true }, { letter: "C", text: "Todo servidor público é ineficiente ou indedicado.", isCorrect: false }, { letter: "D", text: "Algum servidor público não é eficiente e não é dedicado.", isCorrect: false }, { letter: "E", text: "Existe servidor que é eficiente mas não é dedicado.", isCorrect: false }] },
    ],
  },

  {
    name: "Direito Constitucional",
    weeklyHours: 4,
    priority: 1,
    flashcards: [
      { question: "Quais são os fundamentos da República? (Art. 1º CF)", answer: "SOCIP: Soberania, Cidadania, Dignidade da pessoa humana, Valores sociais do trabalho, Pluralismo político." },
      { question: "O que estabelece o §1º do art. 5º CF?", answer: "As normas definidoras dos direitos e garantias fundamentais têm APLICAÇÃO IMEDIATA." },
      { question: "Quando pode haver entrada forçada em domicílio com mandado judicial?", answer: "SOMENTE DURANTE O DIA. Flagrante, desastre e socorro podem ocorrer a qualquer hora." },
      { question: "Racismo é inafiançável e prescritível ou imprescritível?", answer: "IMPRESCRITÍVEL (art. 5º, XLII CF). Um dos poucos crimes imprescritíveis." },
      { question: "Qual a diferença entre competência exclusiva e privativa da União?", answer: "Exclusiva (art. 21): indelegável. Privativa (art. 22): pode ser delegada a Estados por Lei Complementar." },
    ],
    lessons: [
      { title: "Princípios Fundamentais — Arts. 1º ao 4º", topic: "Princípios Fundamentais", type: "video", duration: 15, content: `TÍTULO I — PRINCÍPIOS FUNDAMENTAIS\n\nART. 1º — FUNDAMENTOS (memorize: SOCIP)\nS — Soberania\nO — Cidadania\nC — Dignidade da pessoa humana\nI — Valores sociais do trabalho e da livre iniciativa\nP — Pluralismo político\n\nForma de governo: REPÚBLICA\nSistema de governo: PRESIDENCIALISMO\nForma de Estado: FEDERAÇÃO (união indissolúvel)\nTodo poder emana do POVO (§ único)\n\nART. 2º — SEPARAÇÃO DOS PODERES\nLegislativo | Executivo | Judiciário\nIndependentes E harmônicos entre si\n\nART. 3º — OBJETIVOS FUNDAMENTAIS\nI — Construir sociedade livre, justa e solidária\nII — Garantir o desenvolvimento nacional\nIII — Erradicar a pobreza e reduzir desigualdades\nIV — Promover o bem de todos SEM preconceitos\n\nART. 4º — RELAÇÕES INTERNACIONAIS\n• Independência nacional\n• Prevalência dos direitos humanos\n• Autodeterminação dos povos\n• Não-intervenção\n• Igualdade entre os Estados\n• Defesa da paz\n• Solução pacífica dos conflitos\n• Repúdio ao terrorismo e ao racismo\n• Cooperação entre os povos\n• Concessão de asilo político\n§ único: Busca integração da América Latina` },
      { title: "Direitos Fundamentais — Art. 5º CF", topic: "Direitos Fundamentais", type: "reading", duration: 25, content: `ART. 5º — O MAIS COBRADO EM CONCURSOS\n\nCAPUT: Todos são iguais perante a lei...\n→ Aplica-se a: BRASILEIROS + ESTRANGEIROS RESIDENTES\n→ 5 direitos básicos: Vida · Liberdade · Igualdade · Segurança · Propriedade\n\nINSOS MAIS COBRADOS:\n\nI — Igualdade entre homens e mulheres (direitos e obrigações)\nII — Legalidade: ninguém obrigado a fazer/deixar de fazer sem lei\nIV — Livre manifestação do pensamento (VEDADO anonimato)\nVI — Liberdade de consciência e crença\nX — Inviolabilidade: intimidade, vida privada, honra, imagem\nXI — Inviolabilidade do lar\n   Regra: INVIOLÁVEL\n   Exceções: consentimento | flagrante delito | desastre | socorro\n   + mandado judicial (SOMENTE DE DIA)\nXII — Sigilo das comunicações (exceto por ordem judicial penal)\nXXXVII — VEDADO tribunal de exceção\nXXXVIII — Tribunal do júri: soberania, plenitude de defesa,\n           sigilo das votações, crimes DOLOSOS contra a VIDA\nXXXIX — Não há crime sem lei anterior (legalidade penal)\nXL — Lei penal NÃO retroage, SALVO para beneficiar\nXLII — Racismo: inafiançável + IMPRESCRITÍVEL\nXLIII — Hediondos, tortura, tráfico, terrorismo: inafiançáveis\nLVII — Presunção de inocência (até trânsito em julgado)\n\n§1º — Aplicação IMEDIATA dos direitos fundamentais\n§3º — Tratados de DH aprovados com quórum de EC = status constitucional` },
      { title: "Organização do Estado — Federalismo", topic: "Organização do Estado", type: "video", duration: 20, content: `ORGANIZAÇÃO DO ESTADO BRASILEIRO\n\nENTES FEDERATIVOS:\n• União Federal\n• Estados (26 + Distrito Federal)\n• Municípios\n• DF (não pode ser dividido em municípios)\n\nART. 21 — COMPETÊNCIA EXCLUSIVA DA UNIÃO (não delegável):\nPolítica exterior, declarar guerra, moeda, energia nuclear,\nserviços postais, seguro desemprego, imigração, índios\n\nART. 22 — COMPETÊNCIA LEGISLATIVA PRIVATIVA DA UNIÃO:\nPode ser delegada por Lei Complementar\nDireito civil, penal, processual, trabalhista, eleitoral,\ntrânsito, telecomunicações, informática, seguridade social\n\nART. 23 — COMPETÊNCIA COMUM (todos os entes):\nZelar pela CF | Saúde | Meio ambiente | Cultura | Patrimônio\n\nART. 24 — COMPETÊNCIA CONCORRENTE (União + Estados + DF):\n→ Municípios NÃO participam!\nDireito tributário, financeiro, urbanístico, previdenciário,\neconômico, penitenciário | Produção e consumo | Educação\n\nREGRA DO ART. 24:\n• União → normas gerais\n• Estado → suplementa\n• União omissa: Estado legisla plenamente\n• Lei federal superveniente: SUSPENDE (não revoga) lei estadual` },
      { title: "Remédios Constitucionais", topic: "Garantias Fundamentais", type: "reading", duration: 18, content: `REMÉDIOS CONSTITUCIONAIS — QUADRO COMPLETO\n\nHABEAS CORPUS (HC)\nProtege: liberdade de LOCOMOÇÃO\nContra: ameaça ou violência\nQuem: QUALQUER PESSOA (sem advogado)\nPlacar: cabe até por e-mail\n\nMANDADO DE SEGURANÇA (MS)\nProtege: direito LÍQUIDO E CERTO não amparado por HC/HD\nContra: ato ilegal/abusivo de AUTORIDADE PÚBLICA\nPrazo: 120 dias do ato\nExige: advogado\n\nHABEAS DATA (HD)\nProtege: acesso/retificação de dados do PRÓPRIO IMPETRANTE\nOnde: bancos de dados governamentais ou de caráter público\nQuem: somente o TITULAR dos dados\n\nMANDADO DE INJUNÇÃO (MI)\nQuando: falta de norma impede exercício de direito constitucional\nEfeito: STF pode dar efeito inter partes ou erga omnes\n\nAÇÃO POPULAR (AP)\nQuem: CIDADÃO (pessoa física com direitos políticos)\nFinalidade: anular ato lesivo ao patrimônio público,\n           moralidade, meio ambiente, patrimônio cultural\nGratuita: autor isento de custas (salvo má-fé)\n\nAÇÃO CIVIL PÚBLICA (ACP)\nQuem: MP, Defensoria, sindicatos, associações, entes políticos\nFinalidade: proteção de interesses difusos e coletivos` },
    ],
    questions: [
      { topic: "Princípios Fundamentais", content: "Segundo o art. 1º da CF/88, são fundamentos da República Federativa do Brasil:", banca: "CESPE", difficulty: "easy", year: 2023, explanation: "Fundamentos: SOCIP — Soberania, Cidadania, Dignidade da pessoa humana, Valores sociais do trabalho e da livre iniciativa, Pluralismo político.", options: [{ letter: "A", text: "Soberania, cidadania, dignidade da pessoa humana, valores sociais do trabalho e da livre iniciativa e pluralismo político.", isCorrect: true }, { letter: "B", text: "Soberania, cidadania, separação dos poderes, livre iniciativa e pluralismo político.", isCorrect: false }, { letter: "C", text: "Democracia, cidadania, dignidade humana, trabalho e pluralismo.", isCorrect: false }, { letter: "D", text: "Soberania, igualdade, dignidade, trabalho e legalidade.", isCorrect: false }, { letter: "E", text: "Federalismo, cidadania, dignidade, livre iniciativa e democracia.", isCorrect: false }] },
      { topic: "Direitos Individuais", content: "Sobre a inviolabilidade do domicílio (art. 5º, XI, CF/88), é CORRETO afirmar:", banca: "FCC", difficulty: "medium", year: 2024, explanation: "A entrada por mandado judicial só pode ocorrer DURANTE O DIA. Flagrante delito, desastre e prestar socorro podem ocorrer a qualquer hora.", options: [{ letter: "A", text: "A entrada com mandado judicial pode ocorrer a qualquer hora.", isCorrect: false }, { letter: "B", text: "A entrada por mandado judicial só é permitida durante o dia.", isCorrect: true }, { letter: "C", text: "Em flagrante delito, a entrada só é permitida durante o dia.", isCorrect: false }, { letter: "D", text: "A inviolabilidade do lar é absoluta, sem exceções.", isCorrect: false }, { letter: "E", text: "Para prestar socorro, é necessário mandado judicial.", isCorrect: false }] },
      { topic: "Competências", content: "Sobre as competências legislativas no federalismo brasileiro, é CORRETO afirmar:", banca: "FCC", difficulty: "hard", year: 2024, explanation: "No art. 24 (competência concorrente), a superveniência de lei federal SUSPENDE (não revoga) a lei estadual no que lhe for contrário. Se a União for omissa, o Estado pode legislar plenamente.", options: [{ letter: "A", text: "A superveniência de lei federal suspende a eficácia da lei estadual no que lhe for contrário.", isCorrect: true }, { letter: "B", text: "A lei federal revoga definitivamente a lei estadual conflitante.", isCorrect: false }, { letter: "C", text: "Municípios participam da competência concorrente do art. 24.", isCorrect: false }, { letter: "D", text: "A competência exclusiva da União pode ser delegada por lei ordinária.", isCorrect: false }, { letter: "E", text: "Estados não podem legislar sobre matéria de competência privativa da União.", isCorrect: false }] },
    ],
  },

  {
    name: "Direito Administrativo",
    weeklyHours: 3,
    priority: 2,
    flashcards: [
      { question: "Quais são os princípios da Administração Pública? (LIMPE)", answer: "Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência (art. 37 CF)." },
      { question: "O que é ato administrativo vinculado?", answer: "Ato em que a lei define todos os elementos: competência, forma, finalidade, motivo e objeto. Sem margem de escolha." },
      { question: "O que é poder discricionário?", answer: "Poder de a Administração escolher, dentro dos limites da lei, a oportunidade e conveniência do ato. Avalia o mérito administrativo." },
      { question: "Quais são os atributos do ato administrativo?", answer: "PATI: Presunção de legitimidade/veracidade, Autoexecutoriedade, Tipicidade, Imperatividade." },
      { question: "O que é licitação na modalidade pregão?", answer: "Modalidade usada para bens e serviços comuns, com disputa pelo menor preço via lances verbais ou eletrônicos. Invertida (proposta antes da habilitação)." },
    ],
    lessons: [
      { title: "Princípios da Administração Pública", topic: "Princípios", type: "video", duration: 15, content: `PRINCÍPIOS DA ADMINISTRAÇÃO PÚBLICA\n\nART. 37 CF — PRINCÍPIOS EXPRESSOS (LIMPE):\n\nL — LEGALIDADE\nO agente público só pode fazer o que a lei AUTORIZA.\n(Diferente do particular: pode fazer tudo que a lei NÃO proíbe)\n\nI — IMPESSOALIDADE\n• Proibição de favorecimento pessoal\n• Imputação dos atos à ADMINISTRAÇÃO, não ao agente\n• Proibição de promoção pessoal com publicidade oficial\n• Princípio da finalidade: atos devem visar ao interesse público\n\nM — MORALIDADE\n• Conduta ética e probidade administrativa\n• Boa-fé, lealdade, honestidade\n• Lei de Improbidade Administrativa (Lei 8.429/92)\n\nP — PUBLICIDADE\n• Atos administrativos devem ser divulgados\n• Regra: publicidade | Exceção: sigilo (segurança nacional, intimidade)\n• Sem publicidade, o ato não produz efeitos externos\n\nE — EFICIÊNCIA\n• Incluído pela EC 19/98 (Reforma Administrativa)\n• Melhor resultado com menor custo\n• Avaliação periódica de desempenho\n• Perda do cargo por insuficiência de desempenho\n\nPRINCÍPIOS IMPLÍCITOS:\n• Razoabilidade/proporcionalidade\n• Continuidade do serviço público\n• Segurança jurídica\n• Motivação\n• Autotutela (Súmula 473 STF: Adm. pode anular ou revogar seus atos)` },
      { title: "Atos Administrativos", topic: "Atos Administrativos", type: "reading", duration: 20, content: `ATOS ADMINISTRATIVOS\n\nELEMENTOS (requisitos de validade):\n• COMPETÊNCIA: quem pratica o ato (vinculado)\n• FORMA: como o ato é exteriorizado (vinculado)\n• FINALIDADE: resultado que se quer alcançar (vinculado — sempre interesse público)\n• MOTIVO: situação de fato e de direito que autoriza o ato (pode ser discricionário)\n• OBJETO: conteúdo do ato (pode ser discricionário)\n\nATRIBUTOS (características):\n• PRESUNÇÃO DE LEGITIMIDADE/VERACIDADE: ato é válido até prova em contrário\n• IMPERATIVIDADE: cria obrigações independente de concordância\n• AUTOEXECUTORIEDADE: pode ser executado diretamente sem o Judiciário\n  Exceção: cobrança de multas (precisa do Judiciário)\n• TIPICIDADE: ato deve corresponder a figuras definidas em lei\n\nVICIOS DO ATO ADMINISTRATIVO:\n• NULIDADE: ato com vício de legalidade → ANULADO (efeito ex tunc)\n• REVOGAÇÃO: ato legal, mas inconveniente/inoportunamente → REVOGADO (ex nunc)\n• Prazo para anulação: 5 anos (se má-fé: imprescritível)\n\nEspécies:\n• NORMATIVO: regulamento, portaria geral\n• ORDINATÓRIO: circular, memorando, ordem de serviço\n• NEGOCIAL: licença, autorização, permissão\n• ENUNCIATIVO: certidão, atestado, parecer\n• PUNITIVO: multa, interdição, demissão` },
      { title: "Licitação — Lei 14.133/2021", topic: "Licitação", type: "video", duration: 22, content: `LICITAÇÃO — NOVA LEI (14.133/2021)\n\nOBJETIVO: selecionar a proposta mais vantajosa para a Adm. Pública.\n\nMODALIDADES:\n• PREGÃO: bens e serviços comuns, disputa pelo menor preço\n  Eletrônico (preferencial) ou presencial\n  Fase invertida: proposta ANTES da habilitação\n\n• CONCORRÊNCIA: objetos de alto valor e obras\n  Critérios: menor preço, maior desconto, melhor técnica,\n             técnica e preço, maior lance ou oferta, maior retorno econômico\n\n• CONCURSO: escolha de trabalho técnico/científico/artístico\n  Prêmio ou remuneração\n\n• LEILÃO: bens imóveis ou bens móveis inservíveis\n  Maior lance\n\n• DIÁLOGO COMPETITIVO: objetos inovadores e complexos\n  Novo na lei 14.133/2021\n\nDISPENSA DE LICITAÇÃO (exemplos principais):\n• Valor (compras/serviços): até R$ 50.000\n• Valor (obras): até R$ 100.000\n• Emergência/calamidade (prazo: 30 dias para obras, 6 meses para serviços)\n• Contratação com outros órgãos da Adm. Pública\n\nINEXIGIBILIDADE (competição inviável):\n• Fornecedor exclusivo\n• Serviços técnicos especializados (lista taxativa)\n• Artistas consagrados pela mídia` },
      { title: "Agentes Públicos e Responsabilidade", topic: "Agentes Públicos", type: "reading", duration: 18, content: `AGENTES PÚBLICOS\n\nCLASSIFICAÇÃO:\n• AGENTES POLÍTICOS: exercem funções de governo\n  (Presidente, ministros, parlamentares, juízes)\n• SERVIDORES PÚBLICOS: vínculo funcional permanente\n  - Estatutários: regime próprio (CLT não se aplica)\n  - Celetistas: regime CLT\n  - Temporários: contrato por prazo determinado\n• PARTICULARES EM COLABORAÇÃO: sem vínculo\n  (mesários, jurados, concessionários)\n\nESTABILIDADE (servidores estatutários):\n• Efetivo: aprovado em concurso público\n• Estágio probatório: 3 anos\n• Adquire estabilidade após 3 anos de exercício\n• Perda da estabilidade: processo administrativo, judicial ou\n  avaliação periódica de desempenho insuficiente\n\nREMUNERACÃO E SUBSÍDIO:\n• Teto remuneratório: subsídio dos Ministros do STF\n• Subsídio: parcela única (vedado acréscimo)\n\nRESPONSABILIDADE CIVIL DO ESTADO:\n• TEORIA OBJETIVA (responsabilidade sem culpa)\n• Art. 37, §6º CF: Estado responde pelos danos de seus agentes\n• Basta: conduta, dano e nexo causal\n• Exceção: atos omissivos → teoria subjetiva (precisa provar culpa)\n• Direito de regresso: Estado cobra do agente se este agiu com dolo/culpa\n\nImprobidade Administrativa (Lei 8.429/92):\n• Enriquecimento ilícito, dano ao erário, violação dos princípios\n• Sanções: perda do cargo, suspensão dos direitos políticos, multa, ressarcimento` },
    ],
    questions: [
      { topic: "Princípios", content: "O princípio da legalidade, aplicado à Administração Pública, significa que:", banca: "CESPE", difficulty: "easy", year: 2023, explanation: "O princípio da legalidade para a Administração Pública é diferente do aplicado ao particular. O agente público só pode fazer o que a lei EXPRESSAMENTE AUTORIZA, ao contrário do particular, que pode fazer tudo que a lei não proíbe.", options: [{ letter: "A", text: "O administrador pode fazer tudo o que a lei não proíbe.", isCorrect: false }, { letter: "B", text: "O administrador só pode agir quando expressamente autorizado por lei.", isCorrect: true }, { letter: "C", text: "A administração pode agir por conveniência, desde que não viole a lei.", isCorrect: false }, { letter: "D", text: "O agente público pode praticar atos discricionários sem base legal.", isCorrect: false }, { letter: "E", text: "A legalidade só se aplica a atos vinculados.", isCorrect: false }] },
      { topic: "Atos Administrativos", content: "Sobre os atributos do ato administrativo, assinale a alternativa CORRETA:", banca: "FCC", difficulty: "medium", year: 2023, explanation: "A autoexecutoriedade permite à Administração executar seus atos independentemente de autorização judicial. Exceção: cobrança de multas, que precisam do Judiciário. A presunção de legitimidade é relativa (iuris tantum), admitindo prova em contrário.", options: [{ letter: "A", text: "A presunção de legitimidade é absoluta e não admite prova em contrário.", isCorrect: false }, { letter: "B", text: "A autoexecutoriedade permite à Administração executar atos sem intervenção judicial.", isCorrect: true }, { letter: "C", text: "Todo ato administrativo é dotado de autoexecutoriedade, inclusive a cobrança de multas.", isCorrect: false }, { letter: "D", text: "A imperatividade exige a concordância do administrado para produzir efeitos.", isCorrect: false }, { letter: "E", text: "A tipicidade aplica-se apenas aos atos discricionários.", isCorrect: false }] },
      { topic: "Licitação", content: "Na modalidade pregão, introduzida na nova Lei de Licitações (14.133/2021), ocorre:", banca: "CESPE", difficulty: "medium", year: 2024, explanation: "O pregão tem fase INVERTIDA: primeiro as propostas são analisadas, depois é feita a habilitação apenas do vencedor. Isso torna o processo mais rápido. É usado para bens e serviços comuns.", options: [{ letter: "A", text: "Habilitação antes da análise das propostas, como nas demais modalidades.", isCorrect: false }, { letter: "B", text: "Disputa pelo maior valor, para maximizar a arrecadação estatal.", isCorrect: false }, { letter: "C", text: "Fase invertida: proposta antes da habilitação, para maior celeridade.", isCorrect: true }, { letter: "D", text: "Uso exclusivo para obras e serviços de engenharia.", isCorrect: false }, { letter: "E", text: "Ausência de disputa, com seleção pelo critério técnico.", isCorrect: false }] },
    ],
  },

  {
    name: "Matemática",
    weeklyHours: 3,
    priority: 2,
    flashcards: [
      { question: "Fórmula do juros simples?", answer: "J = C × i × t, onde C = capital, i = taxa (na mesma unidade do tempo), t = tempo." },
      { question: "Fórmula do juros compostos?", answer: "M = C × (1 + i)^t, onde M = montante, C = capital, i = taxa, t = tempo." },
      { question: "Como calcular porcentagem de aumento?", answer: "Novo valor = Valor original × (1 + taxa%). Ex: 20% de aumento → × 1,20." },
      { question: "Fórmula da média aritmética ponderada?", answer: "MAP = (x1×p1 + x2×p2 + ... + xn×pn) / (p1 + p2 + ... + pn)." },
      { question: "O que é MMC e MDC?", answer: "MMC: menor número divisível por todos. MDC: maior número que divide todos. Usados em frações e problemas de divisão." },
    ],
    lessons: [
      { title: "Porcentagem e Razão", topic: "Porcentagem", type: "video", duration: 16, content: `PORCENTAGEM — FUNDAMENTOS\n\nDEFINIÇÃO: razão com denominador 100.\n40% = 40/100 = 0,40\n\nCONVERSÕES:\n• % → decimal: divide por 100 (40% = 0,40)\n• decimal → %: multiplica por 100 (0,75 = 75%)\n• % → fração: 25% = 25/100 = 1/4\n\nCALCULOS FUNDAMENTAIS:\n1. X% de N = (X/100) × N\n   Ex: 15% de 200 = 0,15 × 200 = 30\n\n2. N é X% de M → N = (X/100) × M → M = N × (100/X)\n   Ex: 30 é 15% de quanto? M = 30 × (100/15) = 200\n\n3. Aumento de X%: novo = original × (1 + X/100)\n   Ex: R$200 com 15% de aumento = 200 × 1,15 = R$230\n\n4. Desconto de X%: novo = original × (1 - X/100)\n   Ex: R$200 com 20% de desconto = 200 × 0,80 = R$160\n\n5. Variação percentual = [(final - inicial)/inicial] × 100\n   Ex: subiu de R$80 para R$100 → [(100-80)/80] × 100 = 25%\n\nAUMENTO + DESCONTO SUCESSIVOS:\nNão são simplesmente somados!\n+20% e -20%: resultado = × 1,20 × 0,80 = × 0,96 = redução de 4%\n\nREGRA DE TRÊS:\nSimples (proporcional): a/b = c/x → x = (b×c)/a\nComposta: multiplica/divide conforme a relação (direta/inversa)` },
      { title: "Juros Simples e Compostos", topic: "Juros", type: "reading", duration: 20, content: `MATEMÁTICA FINANCEIRA\n\nJUROS SIMPLES:\n• J = C × i × t\n• M = C + J = C(1 + i×t)\nOnde: C = capital inicial, i = taxa, t = tempo (mesma unidade)\n\nEXEMPLO:\nR$1.000 a 2% ao mês por 6 meses:\nJ = 1000 × 0,02 × 6 = R$120\nM = 1000 + 120 = R$1.120\n\nJUROS COMPOSTOS (regime mais comum):\n• M = C × (1 + i)^t\n• J = M - C\n\nEXEMPLO:\nR$1.000 a 2% ao mês por 6 meses:\nM = 1000 × (1,02)^6 = 1000 × 1,1262 = R$1.126,16\nJ = 1126,16 - 1000 = R$126,16\n\nTaxa efetiva vs. nominal:\n• Taxa nominal: declarada (12% ao ano)\n• Taxa efetiva: real após capitalização (12% a.a. compostos mensalmente ≠ 1% a.m.)\n\nDESCONTO SIMPLES:\n• Desconto: D = N × d × t\n• Valor presente: VP = N × (1 - d×t)\nOnde N = valor nominal (futuro), d = taxa de desconto, t = tempo\n\nDESCONTO COMPOSTO:\n• VP = N / (1 + i)^t\n\nEQUIVALÊNCIA DE TAXAS:\nTaxas equivalentes produzem o mesmo montante.\n1% a.m. compostos ≠ 12% a.a. compostos (pois há capitalização)` },
      { title: "Estatística e Probabilidade", topic: "Estatística", type: "video", duration: 18, content: `ESTATÍSTICA BÁSICA\n\nMEDIDAS DE POSIÇÃO CENTRAL:\n• MÉDIA ARITMÉTICA: soma ÷ quantidade\n  Ex: {2, 4, 6, 8, 10} → média = 30/5 = 6\n• MEDIANA: valor central (após ordenar)\n  Ímpar: valor do meio\n  Par: média dos dois do meio\n  Ex: {2,4,6,8,10} → mediana = 6\n  Ex: {2,4,6,8} → mediana = (4+6)/2 = 5\n• MODA: valor mais frequente\n  Ex: {2,3,3,4,5} → moda = 3\n  Pode ser bimodal, trimodal ou amodal\n\nMEDIANA vs MÉDIA: mediana não é afetada por valores extremos.\n\nMEDIDAS DE DISPERSÃO:\n• VARIÂNCIA: média dos quadrados dos desvios\n• DESVIO PADRÃO: raiz da variância (mesma unidade dos dados)\n\nPROBABILIDADE:\n• P(A) = casos favoráveis / casos totais\n• 0 ≤ P(A) ≤ 1\n• P(A') = 1 - P(A) [evento complementar]\n• P(A∪B) = P(A) + P(B) - P(A∩B)\n• Eventos independentes: P(A∩B) = P(A) × P(B)\n\nANÁLISE COMBINATÓRIA:\n• PERMUTAÇÃO: P(n) = n!\n• ARRANJO: A(n,k) = n!/(n-k)!\n• COMBINAÇÃO: C(n,k) = n!/[k!×(n-k)!]\n\nRegra: use combinação quando a ORDEM NÃO IMPORTA.` },
    ],
    questions: [
      { topic: "Porcentagem", content: "Um produto custa R$250,00. Após um aumento de 20% e, em seguida, um desconto de 20%, o preço final será:", banca: "CESPE", difficulty: "medium", year: 2023, explanation: "Aumento de 20%: 250 × 1,20 = 300. Desconto de 20%: 300 × 0,80 = 240. Resultado: R$240. Atenção: aumentos e descontos sucessivos não se anulam! O resultado é uma redução de 4% sobre o preço original.", options: [{ letter: "A", text: "R$250,00 (o preço volta ao original)", isCorrect: false }, { letter: "B", text: "R$240,00", isCorrect: true }, { letter: "C", text: "R$260,00", isCorrect: false }, { letter: "D", text: "R$230,00", isCorrect: false }, { letter: "E", text: "R$245,00", isCorrect: false }] },
      { topic: "Juros", content: "Um capital de R$2.000 é aplicado por 3 meses a juros simples de 4% ao mês. Qual o montante ao final?", banca: "FCC", difficulty: "easy", year: 2022, explanation: "J = C × i × t = 2000 × 0,04 × 3 = R$240. M = C + J = 2000 + 240 = R$2.240.", options: [{ letter: "A", text: "R$2.160", isCorrect: false }, { letter: "B", text: "R$2.200", isCorrect: false }, { letter: "C", text: "R$2.240", isCorrect: true }, { letter: "D", text: "R$2.280", isCorrect: false }, { letter: "E", text: "R$2.320", isCorrect: false }] },
      { topic: "Estatística", content: "As notas de um aluno foram: 6, 7, 8, 9 e 10. A média aritmética e a mediana são, respectivamente:", banca: "VUNESP", difficulty: "easy", year: 2023, explanation: "Média = (6+7+8+9+10)/5 = 40/5 = 8. Mediana = valor central do conjunto ordenado {6,7,8,9,10} = 8. Neste caso, média = mediana = 8.", options: [{ letter: "A", text: "8 e 7", isCorrect: false }, { letter: "B", text: "8 e 8", isCorrect: true }, { letter: "C", text: "7,5 e 8", isCorrect: false }, { letter: "D", text: "8 e 9", isCorrect: false }, { letter: "E", text: "7 e 8", isCorrect: false }] },
    ],
  },

  {
    name: "Informática",
    weeklyHours: 2,
    priority: 3,
    flashcards: [
      { question: "O que é RAM e ROM?", answer: "RAM (memória de acesso aleatório): temporária, volátil, perde ao desligar. ROM: permanente, não volátil, armazena BIOS/firmware." },
      { question: "Diferença entre HTTP e HTTPS?", answer: "HTTP: sem criptografia, porta 80. HTTPS: com criptografia SSL/TLS, porta 443. HTTPS é obrigatório para sites com dados sensíveis." },
      { question: "O que é phishing?", answer: "Golpe digital onde o atacante se faz passar por entidade legítima para roubar dados. Geralmente via e-mail ou site falso." },
      { question: "Atalhos essenciais do Windows?", answer: "Ctrl+C (copiar), Ctrl+V (colar), Ctrl+X (recortar), Ctrl+Z (desfazer), Ctrl+A (selecionar tudo), Alt+F4 (fechar)." },
      { question: "O que é backup e qual o melhor método?", answer: "Cópia de segurança dos dados. Regra 3-2-1: 3 cópias, em 2 mídias diferentes, com 1 cópia fora do local." },
    ],
    lessons: [
      { title: "Hardware e Software — Fundamentos", topic: "Hardware e Software", type: "video", duration: 12, content: `HARDWARE E SOFTWARE\n\nHARDWARE — componentes físicos:\n\nUNIDADE CENTRAL DE PROCESSAMENTO (CPU):\n• Processador: executa instruções\n• Velocidade medida em GHz\n• Núcleos (cores): capacidade de multitarefa\n\nMEMÓRIA:\n• RAM (Random Access Memory): temporária, volátil\n  - Perde os dados quando desligado\n  - Tipos: DDR4, DDR5\n• ROM: permanente, não volátil\n  - Armazena BIOS/UEFI\n• Cache: memória ultrarrápida dentro do processador\n  - L1 > L2 > L3 (velocidade decrescente, tamanho crescente)\n\nARMAZENAMENTO:\n• HD (HDD): magnético, mais lento, mais capacidade por $\n• SSD: memória flash, mais rápido, mais caro por GB\n• Pen drive/cartão SD: portátil, flash\n\nDISPOSITIVOS DE ENTRADA: teclado, mouse, scanner, webcam\nDISPOSITIVOS DE SAÍDA: monitor, impressora, caixas de som\nDISPOSITIVOS MISTOS: tela touch, pen drive\n\nSOFTWARE — programas:\n• Sistema Operacional: Windows, Linux, macOS, Android\n• Aplicativos: Word, Chrome, WhatsApp\n• Drivers: software que faz hardware funcionar\n• Firmware: software gravado em hardware (BIOS)\n\nLICENÇAS:\n• Proprietário: pago, código fechado (Windows, Office)\n• Livre/Open Source: código aberto (Linux, LibreOffice)\n• Freeware: gratuito, código fechado (Adobe Reader)\n• Shareware: experimental, limitado (WinRAR)` },
      { title: "Internet, E-mail e Segurança", topic: "Internet e Segurança", type: "reading", duration: 18, content: `INTERNET E SEGURANÇA DIGITAL\n\nPROTOCOLOS ESSENCIAIS:\n• HTTP: transferência de hipertexto (porta 80) — sem criptografia\n• HTTPS: HTTP com SSL/TLS (porta 443) — com criptografia ✓\n• FTP: transferência de arquivos (porta 21)\n• SMTP: envio de e-mail (porta 25/587)\n• POP3: recebe e-mail, baixa para o PC (porta 110)\n• IMAP: recebe e-mail, mantém no servidor (porta 143)\n• DNS: traduz domínio em IP (porta 53)\n• DHCP: atribui IP automaticamente\n\nTIPOS DE AMEAÇAS:\n• VÍRUS: se replica anexando-se a arquivos\n• WORM: se replica sozinho pela rede, sem arquivo hospedeiro\n• TROJAN (Cavalo de Troia): aparenta ser legítimo, abre portas\n• RANSOMWARE: sequestra dados e exige resgate (ex: WannaCry)\n• SPYWARE: espiona atividades do usuário\n• ADWARE: exibe anúncios indesejados\n• ROOTKIT: se oculta no sistema com privilégios de root\n• PHISHING: engenharia social para roubar dados\n• PHARMING: redireciona usuário para site falso via DNS\n\nMECANISMOS DE PROTEÇÃO:\n• Antivírus: detecta e remove malwares\n• Firewall: filtra tráfego de rede (regras de entrada/saída)\n• VPN: criptografa conexão e esconde IP real\n• Criptografia: transforma dados em código ilegível\n  - Simétrica: mesma chave (AES)\n  - Assimétrica: chave pública/privada (RSA, SSL/TLS)\n• Certificado digital: autentica identidade na internet\n• Autenticação de dois fatores (2FA): senha + código extra\n\nBACKUP — REGRA 3-2-1:\n• 3 cópias dos dados\n• Em 2 mídias diferentes\n• 1 cópia fora do local (offsite ou nuvem)` },
      { title: "Microsoft Office — Word e Excel", topic: "Aplicativos", type: "video", duration: 20, content: `MICROSOFT WORD\n\nATALHOS ESSENCIAIS:\n• Ctrl+B: Negrito | Ctrl+I: Itálico | Ctrl+U: Sublinhado\n• Ctrl+C: Copiar | Ctrl+V: Colar | Ctrl+X: Recortar\n• Ctrl+Z: Desfazer | Ctrl+Y: Refazer\n• Ctrl+A: Selecionar tudo | Ctrl+P: Imprimir\n• Ctrl+S: Salvar | Ctrl+F: Localizar | Ctrl+H: Substituir\n• Ctrl+Home: Início do doc | Ctrl+End: Fim do doc\n• F7: Verificar ortografia\n\nFORMATOS DE ARQUIVO:\n• .docx: padrão Word (Office 2007+)\n• .doc: versão antiga (Office 97-2003)\n• .pdf: portátil, não editável facilmente\n• .odt: LibreOffice Writer\n\nMICROSOFT EXCEL\n\nFÓRMULAS BÁSICAS:\n• =SOMA(A1:A10): soma intervalo\n• =MÉDIA(A1:A10): média aritmética\n• =MÁXIMO(A1:A10): maior valor\n• =MÍNIMO(A1:A10): menor valor\n• =CONT.VALORES(A1:A10): conta células não vazias\n• =CONT.SE(A1:A10;"critério"): conta com condição\n• =SE(condição;verdadeiro;falso): condicional\n• =PROCV(valor;tabela;coluna;0): busca vertical\n\nREFERÊNCIAS:\n• Relativa: A1 (muda ao copiar)\n• Absoluta: $A$1 (não muda ao copiar)\n• Mista: $A1 ou A$1\n\nATALHOS EXCEL:\n• Ctrl+Enter: preenche várias células\n• F2: editar célula | F4: alterna referência absoluta/relativa\n• Ctrl+Shift+Enter: fórmula matricial` },
    ],
    questions: [
      { topic: "Segurança", content: "O ataque cibernético em que o criminoso envia mensagem se passando por entidade confiável para obter dados pessoais da vítima é denominado:", banca: "CESPE", difficulty: "easy", year: 2023, explanation: "Phishing é o ataque de engenharia social em que o atacante se faz passar por uma entidade confiável (banco, empresa, governo) para induzir a vítima a fornecer dados sensíveis. Difere do pharming (que redireciona via DNS) e do ransomware (que sequestra dados).", options: [{ letter: "A", text: "Ransomware", isCorrect: false }, { letter: "B", text: "Spyware", isCorrect: false }, { letter: "C", text: "Phishing", isCorrect: true }, { letter: "D", text: "Rootkit", isCorrect: false }, { letter: "E", text: "Pharming", isCorrect: false }] },
      { topic: "Internet", content: "O protocolo HTTPS difere do HTTP principalmente por:", banca: "FCC", difficulty: "easy", year: 2022, explanation: "HTTPS = HTTP + SSL/TLS (criptografia). Utiliza a porta 443 (HTTP usa porta 80). O certificado digital autentica a identidade do servidor e garante a criptografia da comunicação.", options: [{ letter: "A", text: "Usar a porta 80, enquanto o HTTP usa a porta 443.", isCorrect: false }, { letter: "B", text: "Ser mais lento por não usar compressão de dados.", isCorrect: false }, { letter: "C", text: "Utilizar criptografia SSL/TLS para proteger a comunicação.", isCorrect: true }, { letter: "D", text: "Ser exclusivo para e-mails corporativos.", isCorrect: false }, { letter: "E", text: "Dispensar o uso de certificado digital.", isCorrect: false }] },
      { topic: "Office", content: "No Microsoft Excel, a fórmula =SE(B2>7;\"Aprovado\";\"Reprovado\") retornará 'Aprovado' quando:", banca: "VUNESP", difficulty: "medium", year: 2023, explanation: "A função SE(condição;valor_se_verdadeiro;valor_se_falso) retorna o primeiro valor quando a condição é verdadeira. Aqui, retorna 'Aprovado' quando o valor em B2 for MAIOR QUE 7 (não maior ou igual).", options: [{ letter: "A", text: "B2 for igual a 7.", isCorrect: false }, { letter: "B", text: "B2 for maior ou igual a 7.", isCorrect: false }, { letter: "C", text: "B2 for maior que 7.", isCorrect: true }, { letter: "D", text: "B2 for qualquer número positivo.", isCorrect: false }, { letter: "E", text: "B2 for igual a 'Aprovado'.", isCorrect: false }] },
    ],
  },

  {
    name: "Atualidades",
    weeklyHours: 1,
    priority: 3,
    flashcards: [
      { question: "O que é o Novo PAC?", answer: "Programa de Aceleração do Crescimento relançado em 2023, com R$1,7 trilhão em investimentos em infraestrutura, habitação, saneamento e energia." },
      { question: "O que é o G20?", answer: "Grupo das 20 maiores economias do mundo. Brasil presidiu o G20 em 2024. Foco: combate à fome, desigualdade e mudanças climáticas." },
      { question: "O que é COP?", answer: "Conferência das Partes da Convenção-Quadro das Nações Unidas sobre Mudança do Clima (UNFCCC). COP30 será no Brasil (Belém, 2025)." },
      { question: "O que é Novo Ensino Médio?", answer: "Reforma do Ensino Médio (Lei 13.415/2017) com trilhas de aprofundamento e projeto de vida. Revisado em 2023 pelo MEC após críticas." },
    ],
    lessons: [
      { title: "Brasil: Economia e Políticas Públicas", topic: "Brasil Contemporâneo", type: "reading", duration: 15, content: `BRASIL 2024-2025 — TEMAS RELEVANTES\n\nECONOMIA:\n• Taxa Selic: instrumento do Banco Central para controlar inflação\n  - Selic alta = crédito mais caro, menos consumo, menos inflação\n  - Selic baixa = crédito mais barato, mais consumo, mais inflação\n• IPCA: índice oficial de inflação do Brasil\n• PIB (Produto Interno Bruto): soma de tudo produzido no país\n• Arcabouço fiscal: regras de controle dos gastos públicos (substituiu teto de gastos)\n• Reforma tributária (EC 132/2023): unifica impostos em CBS e IBS\n  Fim do PIS/COFINS, ICMS, ISS → substituídos por IVA dual\n\nPROGRAMAS SOCIAIS:\n• Bolsa Família: renda básica para famílias vulneráveis\n• BPC (Benefício de Prestação Continuada): idosos e deficientes\n• Minha Casa Minha Vida: habitação popular\n• Novo PAC: R$1,7 tri em infraestrutura, saneamento, energia\n\nSAÚDE:\n• SUS (Sistema Único de Saúde): universal, gratuito, público\n  Princípios: universalidade, integralidade, equidade\n• Programa Mais Médicos: combate déficit em áreas remotas\n\nEDUCAÇÃO:\n• ENEM: acesso ao ensino superior (SISU, ProUni, FIES)\n• PNLD: distribuição de livros didáticos\n• Piso salarial dos professores: reajuste anual pelo FUNDEB` },
      { title: "Mundo: Geopolítica e Meio Ambiente", topic: "Geopolítica", type: "video", duration: 14, content: `CENÁRIO MUNDIAL 2024-2025\n\nCONFLITOS:\n• Guerra Rússia-Ucrânia (desde fev/2022)\n  - Impacto: crise energética europeia, inflação global de alimentos\n• Conflito Israel-Gaza (desde out/2023)\n  - Repercussão humanitária e geopolítica no Oriente Médio\n\nGEOPOLÍTICA:\n• G7: 7 maiores democracias industrializadas (EUA, UK, Alemanha, França, Itália, Canadá, Japão)\n• G20: 20 maiores economias — Brasil presidiu em 2024\n  Tema: Combate à fome, desigualdade e mudanças climáticas\n• BRICS: Brasil, Rússia, Índia, China, África do Sul + novos membros\n• ONU: 193 países membros, sede em NY\n  Órgãos: Assembleia Geral, Conselho de Segurança, CIJ, FMI, Banco Mundial\n\nMEIO AMBIENTE:\n• Acordo de Paris (2015): limitar aquecimento a 1,5°C\n• COP: Conferência do Clima\n  COP29: Azerbaijão (2024) | COP30: Belém/PA (novembro 2025)\n• Amazônia: desmatamento, bioeconomia, Fundo Amazônia\n• Queimadas: recordes históricos em 2024 no Brasil\n\nTECNOLOGIA:\n• Inteligência Artificial: ChatGPT, regulação global, impacto no mercado\n• 5G: implementação no Brasil, leilão realizado\n• Marco Civil da Internet (Lei 12.965/2014): direitos e deveres online\n• LGPD (Lei 13.709/2018): proteção de dados pessoais no Brasil` },
    ],
    questions: [
      { topic: "Atualidades Nacionais", content: "A Reforma Tributária aprovada pela Emenda Constitucional 132/2023 tem como principal objetivo:", banca: "CESPE", difficulty: "medium", year: 2024, explanation: "A Reforma Tributária (EC 132/2023) simplifica o sistema tributário brasileiro ao substituir 5 tributos (PIS, Cofins, IPI, ICMS e ISS) por um IVA dual composto pelo CBS (federal) e IBS (estados e municípios), além de criar o Imposto Seletivo.", options: [{ letter: "A", text: "Aumentar a carga tributária para financiar novos programas sociais.", isCorrect: false }, { letter: "B", text: "Simplificar o sistema tributário com a criação de um IVA dual, unificando tributos.", isCorrect: true }, { letter: "C", text: "Eliminar todos os impostos estaduais e municipais.", isCorrect: false }, { letter: "D", text: "Reduzir exclusivamente os impostos sobre renda.", isCorrect: false }, { letter: "E", text: "Criar um imposto único federal para substituir todos os tributos.", isCorrect: false }] },
      { topic: "Meio Ambiente", content: "A COP30, principal conferência mundial sobre mudanças climáticas, está prevista para ocorrer em 2025 na cidade de:", banca: "FCC", difficulty: "easy", year: 2024, explanation: "A COP30 (30ª Conferência das Partes da UNFCCC) está programada para novembro de 2025 em Belém, no Pará, Brasil. Será a primeira COP realizada na Amazônia, com foco em biomas tropicais.", options: [{ letter: "A", text: "Brasília, Distrito Federal.", isCorrect: false }, { letter: "B", text: "Rio de Janeiro, Rio de Janeiro.", isCorrect: false }, { letter: "C", text: "Belém, Pará.", isCorrect: true }, { letter: "D", text: "Manaus, Amazonas.", isCorrect: false }, { letter: "E", text: "São Paulo, São Paulo.", isCorrect: false }] },
    ],
  },
];

export const DEFAULT_EXAM = {
  name: "Concurso INSS 2026",
  examDate: new Date("2026-10-15"),
};
